# Generated by Django 5.0.1 on 2024-02-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vistas_Clases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuaios',
            new_name='Usuarios',
        ),
    ]
