# Generated by Django 4.2.10 on 2024-02-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vistas_Clases', '0002_rename_usuaios_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
    ]
